//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHAIRA_GESTIONRIESGO.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RepositorioUAEntities : DbContext
    {
        public RepositorioUAEntities()
            : base("name=RepositorioUAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<estadoprivilegio> estadoprivilegio { get; set; }
        public virtual DbSet<estadorol> estadorol { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<privilegio> privilegio { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    
        public virtual int SP_ELIMINARARCHIVO(Nullable<int> idmenu)
        {
            var idmenuParameter = idmenu.HasValue ?
                new ObjectParameter("idmenu", idmenu) :
                new ObjectParameter("idmenu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARARCHIVO", idmenuParameter);
        }
    }
}
